wiki-project/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name = "index"),
    path("search", views.search, name = "search"),
    path("random", views.random, name = "random"),
    path("new", views.new_entry, name = "newentry"),
    path("edit/<str:title>", views.edit_entry, name = "editentry"),
    path("<str:title>", views.get_entry, name = "entry")
]

wiki-project/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

wiki-project/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki-project/wiki/encyclopedia/views.py
from xml.dom import ValidationErr
from xml.dom.minidom import CharacterData
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
import markdown2
from django import forms
from django.core.exceptions import ValidationError

from random import randint

from . import util

# /wiki
def index(request):    
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

# /wiki/search
def search(request):
    q = request.GET["q"]
    if util.get_entry(q) != None:
        return HttpResponseRedirect(reverse("wiki:entry", args = [q]))
    entries = []
    for entry in util.list_entries():
        if q in entry:
            entries.append(entry)
    return render(request, "encyclopedia/index.html", {"entries": entries})

# /wiki/<str:title>
def get_entry(request, title):
    title = title.lower()
    entry = util.get_entry(title)
    html = markdown2.markdown(entry)

    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "entry": html
    })


def validate_existence(title):
    if util.get_entry(title.lower()) != None:
        raise ValidationError("There is already a page with this title.")

class NewEntryForm(forms.Form):
    title = forms.CharField(label = "Title", validators = [validate_existence])
    content = forms.CharField(widget = forms.Textarea())

# /wiki/new
def new_entry(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"] #request.POST["title"]
            title = title.lower()

            content = form.cleaned_data["content"] #request.POST["content"]
        
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse("wiki:entry", args = [title]))
    else:
        form = NewEntryForm()
    return render(request, "encyclopedia/new-entry.html", {"form": form})

# /wiki/edit/<str:title>
def edit_entry(request, title):
    if request.method == "POST":
        content = request.POST["content"]
        util.save_entry(title, content)
        return HttpResponseRedirect(reverse("wiki:entry", args = [title]))
    
    form = NewEntryForm(initial={"title": title, "content": util.get_entry(title)})
    form.fields["title"].disabled = True
    return render(request, "encyclopedia/edit-entry.html", {"title": title, "form": form})

# /wiki/random
def random(request):
    entries = util.list_entries()
    random_entry_index = randint(0, len(entries) - 1)
    random_entry_title = entries[random_entry_index]

    return HttpResponseRedirect(reverse("wiki:entry", args = [random_entry_title]))

wiki-project/wiki/encyclopedia/templates/encyclopedia/edit-entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit
{% endblock %}

{% block body %}

    <h2 style = "margin-left: 40px; font-weight: bold;">Edit Page</h2>
    <form action = "{% url 'wiki:editentry' title %}" method = "post">
        {% csrf_token %}
        {{ from.non_field_errors }}
        <ul style = "list-style-type: none;">
            <li>
                {{ form.title.label_tag }}
                {{ form.title }}
                {{ form.title.errors }}
            </li>
            <li>
                <label for = "{{ from.content.id_for_label }}" id = "content-label">Content:</label>
                {{ form.content }}
                {{ form.content.errors }}
            </li>
        </ul>
        <input class = "btn btn-primary save-btn" type = "submit" value = "save">
    </form>

{% endblock %}

wiki-project/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}

    {% autoescape off %}
        {{ entry }}
    {% endautoescape %}
    <a href = "{% url 'wiki:editentry' title %}">Edit</a>
{% endblock %}

wiki-project/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href = "{% url 'wiki:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki-project/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action = "{% url 'wiki:search' %}" method = "get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href = "{% url 'wiki:newentry' %}">Create New Page</a>
                </div>
                <div>
                    <a href = "{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki-project/wiki/encyclopedia/templates/encyclopedia/new-entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}

    <h2 style = "margin-left: 40px; font-weight: bold;">New Page</h2>
    <form action = "{% url 'wiki:newentry' %}" method = "post">
        {% csrf_token %}
        {{ from.non_field_errors }}
        <ul style = "list-style-type: none;">
            <li>
                {{ form.title.label_tag }}
                {{ form.title }}
                {{ form.title.errors }}
            </li>
            <li>
                <label for = "{{ from.content.id_for_label }}" id = "content-label">Content:</label>
                {{ form.content }}
                {{ form.content.errors }}
            </li>
        </ul>
        <input class = "btn btn-primary save-btn" type = "submit" value = "save">
    </form>

{% endblock %}