e-commerce-project/commerce/auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create-listing", views.create_listing, name = "createlisting"),
    path("view-listing/<int:listing_id>", views.listing_view, name = "viewlisting"),
    path("view-watchlist", views.watchlist_view, name = "viewwatchlist"),
    path("add-to-watchlist/<int:listing_id>", views.add_to_watchlist, name = "addtowatchlist"),
    path("close-auction/<int:listing_id>", views.close_auction, name = "closeauction"),
    path("add-comment/<int:listing_id>", views.add_comment, name = "addcomment"),
    path("view-categories", views.categories_view, name = "categories"),
    path("view-category/<str:category>", views.category_view, name = "category")
]

e-commerce-project/commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

e-commerce-project/commerce/auctions/models.py
from email.policy import default
from tkinter import CASCADE
from xml.dom import ValidationErr
from django.contrib.auth.models import AbstractUser
from django.db import models
from datetime import datetime

from django.db.models import Max

from django.core.exceptions import ValidationError


class User(AbstractUser):
    pass

class Listing(models.Model):
    seller = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "listings")
    spectators = models.ManyToManyField(User, related_name = "watchlist", blank = True)

    title = models.CharField(max_length = 128)
    description = models.TextField(max_length = 1024)
    starting_bid = models.IntegerField()
    category = models.CharField(max_length = 50)
    date_time = models.DateTimeField(auto_now = True)
    image = models.ImageField(blank = True)

    active = models.BooleanField(default = True)

    def __str__(self):
        return f"{self.title}"


class Comment(models.Model):
    listing = models.ForeignKey(Listing, on_delete = models.CASCADE, related_name = "comments")
    writer = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "comments")
    
    content = models.TextField(max_length = 1024)
    date_time = models.DateTimeField(auto_now = True)

    def __str__(self):
        return f"{self.writer} => {self.listing}"


class Bid(models.Model):
    bidder = models.ForeignKey(User, on_delete = models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete = models.CASCADE, related_name = "bids")
    
    amount = models.FloatField()

    def __str__(self):
        return f"{self.bidder} => {self.listing} by {self.amount}"

    def clean(self):
        if self.amount <= self.listing.starting_bid:
            raise ValidationError("your bid should be greater than the starting bid")
        if not self.listing.bids:
            if self.amount <= self.listing.bids.aggregate(current_price = Max("amount"))["current_price"]:
                raise ValidationError("your bid should be greater than the current price")
        super().clean()

e-commerce-project/commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.db.models import Max
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.forms import ModelForm, Textarea
from datetime import datetime
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth.decorators import login_required

from .models import User, Listing, Comment, Bid


def index(request):
    return render(request, "auctions/index.html", {
            "listings": Listing.objects.filter(active = True)
            .annotate(current_price = Max("bids__amount"))
            .order_by("date_time")
        })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

class ListingForm(ModelForm):
    class Meta():
        model = Listing
        exclude = ["seller", "spectators", "date_time"]
        widgets = {
            "description": Textarea(attrs = {"rows": 5})
        }


@login_required
def create_listing(request):
    if request.method == "POST":
        modelform = ListingForm(request.POST)
        if modelform.is_valid():
            listing = modelform.save(commit = False)
            listing.seller = request.user
            listing.save()
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "autctions/create-listing.html", {"form": modelform})
    else:
        form = ListingForm()
        return render(request, "auctions/create-listing.html", {"form": form})

class BidForm(ModelForm):
    class Meta:
        model = Bid
        fields = ["amount"]
        widgets = {
            "amount": forms.NumberInput(attrs = {"placeholder": "Bid"})
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]
        widgets = {
            "content": forms.Textarea(attrs = {
                "placeholder": "Write a comment...",
                "cols": 50,
                "rows": 5
            })
        }

def listing_view(request, listing_id):
    listing = Listing.objects.get(pk = listing_id)
    if not listing.active:
        max_bid = listing.bids.aggregate(max_bid = Max("amount"))
        winner = listing.bids.get(amount = max_bid.get("max_bid")).bidder
        message = "Auction has Closed"
        if request.user == winner:
            message += ", You Are The Winner"
        return render(request, "auctions/listing.html", {
            "message": message
        })

    bidform = BidForm()
    commentform = CommentForm()
    if request.method == "POST":
        if request.user.is_authenticated:
            bidform = BidForm(request.POST)
            bidform.instance.bidder = request.user
            bidform.instance.listing = Listing.objects.get(pk = listing_id)
            if bidform.is_valid():
                bidform.save()
                return HttpResponseRedirect(reverse("auctions:viewlisting", args = [listing_id]))
        else:
            return HttpResponseRedirect(reverse("auctions:login"))
            
    return render(request, "auctions/listing.html", {
        "listing": Listing.objects.annotate(current_price = Max("bids__amount")).get(pk = listing_id),
        "comments": Listing.objects.get(pk = listing_id).comments.all(),
        "bidform": bidform,
        "commentform": commentform
    })

@login_required
def watchlist_view(request):
    return render(request, "auctions/watchlist.html", {
        "watchlist": User.objects.get(pk = request.user.id).watchlist.all()
    })

def add_to_watchlist(request, listing_id):
    if request.user.is_authenticated:
        listing = Listing.objects.get(pk = listing_id)
        User.objects.get(pk = request.user.id).watchlist.add(listing)
        return HttpResponseRedirect(reverse("auctions:viewwatchlist"))
    else:
        return HttpResponseRedirect(reverse("auctions:login"))

def close_auction(request, listing_id):
    Listing.objects.filter(pk = listing_id).update(active = False)
    return HttpResponseRedirect(reverse("auctions:viewlisting", args = [listing_id]))

@login_required
def add_comment(request, listing_id):
    if request.method == "POST":
        commentform = CommentForm(request.POST)
        if commentform.is_valid():
            comment = commentform.save(commit = False)
            comment.listing = Listing.objects.get(pk = listing_id)
            comment.writer = request.user
            comment.save()
        return HttpResponseRedirect(reverse("auctions:viewlisting", args = [listing_id]))

def categories_view(request):
    return render(request, "auctions/categories.html", {
        "categories": Listing.objects.values_list("category", flat = True).distinct().all()
    })

def category_view(request, category):
    return render(request, "auctions/category.html", {
        "listings": Listing.objects.filter(category = category)
        .filter(active = True)
        .all()
    })

e-commerce-project/commerce/auctions/templates/auctions/categories.html
{% extends 'auctions/layout.html' %}

{% block body %}

    <h2 style = "margin: 10px;">Categories</h2>
    <ul class = "categories">
        {% for category in categories %}
            <li class = "category"><a href = "{% url 'auctions:category' category %}">{{ category }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

e-commerce-project/commerce/auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block body %}
    
    <h2>Active Listings</h2>
    {% for listing in listings %}
        <div class = "listing">
            {% if listing.image %}
                {% load static %} <img src = "/static/auctions/media/{{listing.image}}">
            {% endif %}

            <div class = "details">
                <h3><b>{{ listing.title }}</b></h3>
                <div><b>Description:</b> {{ listing.description }}</div>
                {% if listing.current_price %}
                    <div><b>Current Price:</b> {{ listing.current_price }}</div>
                {% else %}
                    <div><b>Current Price:</b> {{ listing.starting_bid }}</div>
                {% endif %}
                <div><b>Created:</b> {{ listing.date_time }}</div>
                <a class = "btn btn-primary" href = "{% url 'auctions:viewlisting' listing.id %}">View Details</a>
            </div>
        </div>
    {% empty %}
        <h3 style = "margin: 10px;">There are no active listings for this category.</h3>
    {% endfor %}

{% endblock %}

e-commerce-project/commerce/auctions/templates/auctions/create-listing.html
{% extends 'auctions/layout.html' %}


{% block body %}

    <h2 style = "margin-left: 10px;">Create New Listing</h2>
    <form class = "create-listing-form" action = "{% url 'auctions:createlisting' %}" method = "post">
        {% csrf_token %}
        {% if form.non_field_errors %}
        <div>
            {{ form.non_field_errors }}
        </div>
        {% endif %}

        <div class = "listing-fields">
            {% for field in form %}
            {{ field.label_tag }} {{ field }}
            {% if field.errors %}
                <div>
                    {{ field.errors }}
                </div>
            {% endif %}
            {% endfor %}
        </div>
        <input class = "btn btn-primary create-btn" type = "submit" value = "Create Listing">
    </form>

{% endblock %}

e-commerce-project/commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    
    <h2>Active Listings</h2>
    {% for listing in listings %}
        <div class = "listing">
            {% load static %} <img src = "/static/auctions/media/{{listing.image}}">
            <div class = "details">
                <h3><b>{{ listing.title }}</b></h3>
                <div><b>Description:</b> {{ listing.description }}</div>
                <div><b>Current Price:</b> {{ listing.starting_bid }}</div>
                <div><b>Created:</b> {{ listing.date_time }}</div>
                <a class = "btn btn-primary" href = "#">View Details</a>
            </div>
        </div>
    {% endfor %}

{% endblock %}

e-commerce-project/commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
            </li>
            
            {% if user.is_authenticated %}
                <li class = "nav-item"><a class = "nav-link" href = "{% url 'auctions:viewwatchlist' %}">WatchList</a></li>
                <li class = "nav-item"><a class = "nav-link" href = "{% url 'auctions:createlisting' %}">Create Listing</a></li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

e-commerce-project/commerce/auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block body %}
    
    {% if not message %}
        <div class = "listing">
            {% if listing.image %}
                {% load static %} <img src = "/static/auctions/media/{{listing.image}}">
            {% endif %}

            <div class = "details">
                <h3><b>{{ listing.title }}</b></h3>
                <div class = "listing-fields">
                    <label>Description:</label> <p>{{ listing.description }}</p>
                    {% if listing.current_price %}
                        <label>Current Price:</label> <p>{{ listing.current_price }}</p>
                    {% else %}
                        <label>Current Price:</label> <p>{{ listing.starting_bid }}</p>
                    {% endif %}
                    <label>Created:</label> <p>{{ listing.date_time }}</p>
                    <label>Seller:</label> <p>{{ listing.seller.username }}</p>
                </div>
                <a class = "btn btn-primary" href = "{% url 'auctions:addtowatchlist' listing.id %}">Add to Watchlist</a>
                {% if listing.seller == user %}
                    <a class = "btn btn-primary" href = "{% url 'auctions:closeauction' listing.id %}">Close Auction</a>
                {% endif %}
                
            </div> 
        </div>

        <h3 style = "margin-left: 10px; font-weight: bold;">Place Bid</h3>
        <form class = "place-bid-form" action = "{% url 'auctions:viewlisting' listing.id %}" method = "post">
            {% csrf_token %}
            {{ bidform.amount }}
            {{ bidform.non_field_errors }}
            <input class = "btn btn-primary" type = "submit" value = "Place Bid">
        </form>

        <h3 style = "margin-left: 10px; font-weight: bold;">Comments</h3>
        <div class = "comments">
            {% for comment in comments %}
                <div class = "comment">
                    <div class = "writer">{{ comment.writer }}</div>
                    <div class = "content">{{ comment.content }}</div>
                    <div class = "datetime">{{ comment.datetime }}</div>
                </div>
            {% endfor %}
        </div>
        
        <form class = "write-comment" action = "{% url 'auctions:addcomment' listing.id %}" method = "post">
            {% csrf_token %}
            {{ commentform.content }}
            <input class = "btn btn-primary" type = "submit">
        </form>
       
    {% else %}
        <h1>{{ message }}</h1>
    {% endif %}

{% endblock %}

e-commerce-project/commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

e-commerce-project/commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

e-commerce-project/commerce/auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}
    
    <h2>Watchlist</h2>
    {% for listing in watchlist %}
        <div class = "listing">
            {% if listing.image %}
                {% load static %} <img src = "/static/auctions/media/{{listing.image}}">
            {% endif %}

            <div class = "details">
                <h3><b>{{ listing.title }}</b></h3>
                <div><b>Description:</b> {{ listing.description }}</div>
                {% if listing.current_price %}
                    <div><b>Current Price:</b> {{ listing.current_price }}</div>
                {% else %}
                    <div><b>Current Price:</b> {{ listing.starting_bid }}</div>
                {% endif %}
                <div><b>Created:</b> {{ listing.date_time }}</div>
                <a class = "btn btn-primary" href = "{% url 'auctions:viewlisting' listing.id %}">View Details</a>
            </div>
        </div>
    {% endfor %}

{% endblock %}